type Account {
  id: ID!
  balance: Float!
  currency: String!
}

type Transaction {
  id: ID!
  amount: Float!
  status: String!
  fromAccount: ID!
  toAccount: ID!
}

type Query {
  getAccount(id: ID!): Account
  getAllAccounts: [Account!]!
  getTransaction(id: ID!): Transaction
  getAllTransactions: [Transaction!]!
}

type Mutation {
  createAccount(balance: Float!, currency: String!): Account!
  createTransaction(
    fromAccount: ID!
    toAccount: ID!
    amount: Float!
  ): Transaction!
  updateTransactionStatus(id: ID!, status: String!): Transaction!
}
